# This is a basic workflow to help you get started with Actions

name: Docker Trigger

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - run: curl -v -XPOST -u "${{ secrets.DOCKERHUB_USERNAME}}:${{secrets.BURAK_TOKEN}}" -H "Accept:application/vnd.github.v3+json" https://github.com/METU-KALFA/docker_images/actions/workflows/docker-image.yml/dispatches --data '{"ref":"main"}'
