# This is a basic workflow to help you get started with Actions

name: Docker Trigger

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with: 
        ref: master
    - run: curl \
          -X POST \
          -H "Accept:application/vnd.github.v3+json" \
          https://github.com/METU-KALFA/docker_images/actions/workflows/docker-image.yml/dispathces \
          -d '{"ref":"main"}'
